name: "PhpStan"
description: "A Github Action that runs the phpStan for an Magento Package on every push and pull request."
inputs:
  php_version:
    required: true
    default: "8.1"
    description: "PHP Version to use"
  source_folder:
    required: true
    default: .
    description: "The source folder of the package"
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
      - name: Get Composer Cache Directory
        shell: bash
        working-directory: ${{ inputs.source_folder }}
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - run: composer install
        name: Require and attempt install
        working-directory: ${{ inputs.source_folder }}
        shell: bash
        env:
          COMPOSER_CACHE_DIR: ${{ steps.composer-cache.outputs.dir }}
          COMPOSER_AUTH: ${{ inputs.composer_auth }}
      - run: composer require --dev phpstan/phpstan