name: "PhpStan"
description: "A Github Action that runs the phpStan for an Magento Package on every push and pull request."
inputs:
  php_version:
    required: true
    default: "8.1"
    description: "PHP Version to use"
  magento_version:
    required: true
    default: "2.4.6"
    description: "Magento Version to use"
  source_folder:
    required: true
    default: .
    description: "The source folder of the package"
  composer_auth:
    description: "Composer authentication JSON"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}

    - name: Setup Magento
      uses: cleatsquad/setup-magento@main
      with:
        magento-version: ${{ inputs.magento_version }}
        COMPOSER_AUTH: ${{ inputs.composer_auth }}

