name: CI Workflow

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-static-analysis:
    strategy:
      matrix:
        php_version:
          - 8.1
        magento_version:
          - 2.4.6
    runs-on: ubuntu-latest
    env:
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
      PHPSTAN_LEVEL: 2
      COMPOSER_VERSION: 2
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: extdn/github-actions-m2/magento-phpstan/8.1@master
        with:
          composer_name: cleatsquad/magento2-logstream
      #- name: actions Sniffer
        #uses: actions/phpcs-action@v1
      #- name: Unit Tests
        #uses: actions/phpunit-action@v1

  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests with Magento 2 (Php7.4)
        uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
        with:
          module_name: CleatSquad_LogStream
          composer_name: cleatsquad/magento2-logstream
          ce_version: '2.4.6'
      #- name: Mftf test
        #uses: actions/mftf-action@v1