name: CI Workflow

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-static-analysis:
    strategy:
      matrix:
        php_version:
          - 8.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: actions/phpstan@v1
      #- name: actions Sniffer
        #uses: actions/phpcs-action@v1
      #- name: Unit Tests
        #uses: actions/phpunit-action@v1

  #functional-tests:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- name: Mftf test
        #uses: actions/mftf-action@v1