name: CI Workflow

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-static-analysis:
    strategy:
      matrix:
        php_version:
          - 8.1
        magento_version:
          - 2.4.6
    runs-on: ubuntu-latest
    env:
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
      PHPSTAN_LEVEL: 2
      COMPOSER_VERSION: 2
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: extdn/github-actions-m2/magento-phpstan/8.1@master
        with:
          composer_name: cleatsquad/magento2-logstream
      #- name: actions Sniffer
        #uses: actions/phpcs-action@v1
      #- name: Unit Tests
        #uses: actions/phpunit-action@v1

  functional-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests with Magento 2 (Php 8.1)
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: CleatSquad_LogStream
          composer_name: cleatsquad/magento2-logstream
          ce_version: '2.4.6'
      #- name: Mftf test
        #uses: actions/mftf-action@v1